[project]
name = "improc"
version = "0.1.0"
dependencies = [
    "matplotlib",
]

[project.urls]
Repository = "https://github.com/Arktetra/improc.git"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
